name2edibility = {'Agaricus arvensis': 'Edible',
  'Agaricus augustus': 'Edible',
  'Agaricus bernardii': 'Edible',
  'Agaricus bisporus': 'Edible',
  'Agaricus bitorquis': 'Edible',
  'Agaricus bohusii': 'Edible',
  'Agaricus brunneolus': 'Non Edible',
  'Agaricus campestris': 'Edible',
  'Agaricus crocodilinus': 'Edible',
  'Agaricus cupreobrunneus': 'Edible',
  'Agaricus dulcidulus': 'Edible',
  'Agaricus impudicus': 'Non Edible',
  'Agaricus langei': 'Edible',
  'Agaricus lanipes': 'Non Edible',
  'Agaricus litoralis': 'Edible',
  'Agaricus moelleri': 'Poisonous',
  'Agaricus subfloccosus': 'Edible',
  'Agaricus subperonatus': 'Edible',
  'Agaricus sylvaticus': 'Edible',
  'Agaricus sylvicola': 'Edible',
  'Agaricus xanthodermus': 'Poisonous',
  'Amanita ceciliae': 'Edible',
  'Amanita citrina': 'Non Edible',
  'Amanita crocea': 'Edible',
  'Amanita excelsa': 'Non Edible',
  'Amanita franchetii': 'Poisonous',
  'Amanita fulva': 'Edible',
  'Amanita gemmata': 'Non Edible',
  'Amanita lividopallescens': 'Non Edible',
  'Amanita muscaria': 'Poisonous',
  'Amanita pantherina': 'Poisonous',
  'Amanita phalloides': 'Poisonous',
  'Amanita porphyria': 'Poisonous',
  'Amanita rubescens': 'Edible',
  'Amanita strobiliformis': 'Edible',
  'Amanita submembranacea': 'Non Edible',
  'Amanita vaginata': 'Edible',
  'Amanita virosa': 'Poisonous',
  'Boletus aereus': 'Edible',
  'Boletus edulis': 'Edible',
  'Boletus ferrugineus': 'Edible',
  'Boletus pinophilus': 'Edible',
  'Boletus reticulatus': 'Edible',
  'Boletus subtomentosus': 'Edible',
  'Clitocybe agrestis': 'Non Edible',
  'Clitocybe costata': 'Edible',
  'Clitocybe diatreta': 'Poisonous',
  'Clitocybe fragrans': 'Poisonous',
  'Clitocybe gibba': 'Edible',
  'Clitocybe metachroa': 'Non Edible',
  'Clitocybe nebularis': 'Non Edible',
  'Clitocybe odora': 'Edible',
  'Clitocybe phaeophthalma': 'Poisonous',
  'Clitocybe phyllophila': 'Poisonous',
  'Clitocybe rivulosa': 'Poisonous',
  'Clitocybe squamulosa': 'Non Edible',
  'Clitocybe vibecina': 'Non Edible',
  'Mycena abramsii': 'Non Edible',
  'Mycena acicula': 'Non Edible',
  'Mycena aetites': 'Non Edible',
  'Mycena amicta': 'Non Edible',
  'Mycena arcangeliana': 'Non Edible',
  'Mycena aurantiomarginata': 'Non Edible',
  'Mycena capillaripes': 'Non Edible',
  'Mycena capillaris': 'Non Edible',
  'Mycena chlorantha': 'Non Edible',
  'Mycena cinerella': 'Non Edible',
  'Mycena citrinomarginata': 'Non Edible',
  'Mycena clavicularis': 'Non Edible',
  'Mycena clavularis': 'Non Edible',
  'Mycena crocata': 'Non Edible',
  'Mycena diosma': 'Non Edible',
  'Mycena epipterygia': 'Non Edible',
  'Mycena erubescens': 'Non Edible',
  'Mycena filopes': 'Non Edible',
  'Mycena flavescens': 'Non Edible',
  'Mycena galericulata': 'Non Edible',
  'Mycena galopus': 'Non Edible',
  'Mycena haematopus': 'Non Edible',
  'Mycena inclinata': 'Non Edible',
  'Mycena juniperina': 'Non Edible',
  'Mycena leptocephala': 'Non Edible',
  'Mycena luteovariegata': 'Non Edible',
  'Mycena megaspora': 'Non Edible',
  'Mycena meliigena': 'Non Edible',
  'Mycena metata': 'Non Edible',
  'Mycena olivaceomarginata': 'Non Edible',
  'Mycena pelianthina': 'Poisonous',
  'Mycena polygramma': 'Non Edible',
  'Mycena pseudocorticola': 'Non Edible',
  'Mycena pterigena': 'Non Edible',
  'Mycena pura': 'Poisonous',
  'Mycena purpureofusca': 'Non Edible',
  'Mycena renati': 'Non Edible',
  'Mycena rosea': 'Poisonous',
  'Mycena rosella': 'Non Edible',
  'Mycena rubromarginata': 'Non Edible',
  'Mycena sanguinolenta': 'Non Edible',
  'Mycena silvae-nigrae': 'Non Edible',
  'Mycena stipata': 'Non Edible',
  'Mycena stylobates': 'Non Edible',
  'Mycena tenerrima': 'Non Edible',
  'Mycena tintinnabulum': 'Non Edible',
  'Mycena vitilis': 'Non Edible',
  'Mycena vulgaris': 'Non Edible',
  'Russula acrifolia': 'Non Edible',
  'Russula adusta': 'Non Edible',
  'Russula aeruginea': 'Edible',
  'Russula amoenolens': 'Non Edible',
  'Russula atropurpurea': 'Non Edible',
  'Russula atrorubens': 'Non Edible',
  'Russula aurea': 'Edible',
  'Russula aurora': 'Edible',
  'Russula betularum': 'Non Edible' ,
  'Russula brunneoviolacea': 'Edible',
  'Russula caerulea': 'Edible',
  'Russula cessans': 'Edible',
  'Russula chloroides': 'Non Edible',
  'Russula claroflava': 'Edible',
  'Russula cuprea': 'Non Edible',
  'Russula curtipes': 'Edible',
  'Russula cyanoxantha': 'Edible',
  'Russula decolorans': 'Edible',
  'Russula delica': 'Non Edible',
  'Russula densifolia': 'Non Edible',
  'Russula depallens': 'Edible',
  'Russula emetica': 'Poisonous',
  'Russula faginea': 'Edible',
  'Russula farinipes': 'Non Edible',
  'Russula faustiana': 'Non Edible',
  'Russula fellea': 'Poisonous',
  'Russula foetens': 'Non Edible',
  'Russula fragilis': 'Non Edible',
  'Russula grata': 'Non Edible',
  'Russula graveolens': 'Edible',
  'Russula grisea': 'Edible',
  'Russula heterophylla': 'Edible',
  'Russula illota': 'Non Edible',
  'Russula insignis': 'Non Edible',
  'Russula integra': 'Edible',
  'Russula ionochlora': 'Edible',
  'Russula laccata': 'Non Edible',
  'Russula laeta': 'Edible',
  'Russula luteotacta': 'Non Edible',
  'Russula maculata': 'Non Edible',
  'Russula melliolens': 'Edible',
  'Russula nauseosa': 'Non Edible',
  'Russula nitida': 'Non Edible',
  'Russula nobilis': 'Poisonous',
  'Russula ochroleuca': 'Non Edible',
  'Russula odorata': 'Edible',
  'Russula olivacea': 'Non Edible',
  'Russula paludosa': 'Edible',
  'Russula parazurea': 'Edible',
  'Russula pelargonia': 'Non Edible',
  'Russula pseudointegra': 'Non Edible',
  'Russula puellaris': 'Non Edible',
  'Russula queletii': 'Non Edible',
  'Russula risigallina': 'Edible',
  'Russula romellii': 'Edible',
  'Russula rosea': 'Edible',
  'Russula roseoaurantia': 'Non Edible',
  'Russula sanguinea': 'Non Edible',
  'Russula sardonia': 'Non Edible',
  'Russula seperina': 'Non Edible',
  'Russula silvestris': 'Non Edible',
  'Russula solaris': 'Non Edible',
  'Russula sororia': 'Non Edible',
  'Russula subrubens': 'Non Edible',
  'Russula velenovskyi': 'Edible',
  'Russula versicolor': 'Non Edible',
  'Russula vesca': 'Edible',
  'Russula veternosa': 'Non Edible',
  'Russula violeipes': 'Edible',
  'Russula virescens': 'Edible',
  'Russula viscida': 'Non Edible',
  'Russula xerampelina': 'Edible'}